### ISSUE TITLE
Saitek ProFlight Rudder Pedals : modifications update only 2 axis while 3 axis are detected

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#592]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* ~~[Fix bug on Saitek rudder pedals (SDL_mmjoystick.c, application/octet-stream, 2010-08-23 08:58:56 +0000, 11506 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=536)~~
* [Updated patch (SDL_mmjoystick.patch, text/plain, 2014-12-12 02:59:45 +0000, 1103 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=1967)

**Reported in version:** 1.2.14
**Reported for operating system, platform:** Windows (XP), x86

# Comments on the original bug report:

On 2010-08-23 08:58:56 +0000,  wrote:

> Created attachment 536
> Fix bug on Saitek rudder pedals
> 
> On Saitek ProFlight Rudder Pedals, there are 3 axis detected by SDL (left pedal, right pedal and rotation between the 2 pedals around Z axis). But when rudder is used, SDL updates only values for left and right pedals, rotation value is never changed. This behavior has been seen with SDL 1.2.14 on Windows XP SP 2.
> 
> This problem has already been noticed here :
> http://www.orbiterwiki.org/wiki/FlyByWireEGCS#Saitek_Pro_Flight_Rudder_Pedals
> http://www.orbiter-forum.com/showthread.php?t=10010
> 
> It is not a driver problem, because when I launch driver's test GUI, I can see that all movements are detected.
> 
> After some code analysis, I think that I find the problem : MS API sends updated values in JOYINFOEX structure as following (for this rudder device) :
> dwXpos : left pedal
> dwYpos : right pedal
> dwZpos : nothing
> dwRpos : pedals rotation
> dwUpos : nothing
> dwVpos : nothing
> 
> There are 3 values but the third one is not at the third position in this structure. So the code seems easy to fix in SDL_mmjoystick.c in SDL_SYS_JoystickUpdate(SDL_Joystick* joystick) function. I attach my own version of this file which has been successfully tested for this device and with some others (on Window XP only).
> 
> Hope this can help.

On 2011-04-12 20:18:06 +0000, Jen Spradlin wrote:

> Thank you for your bug report!
> 
> We're busy working on getting SDL 1.3 ready for a high quality release, and want to make sure as many things are fixed there as possible.
> Could you check to see if your bug is resolved by the latest SDL 1.3 snapshot?
> http://www.libsdl.org/tmp/SDL-1.3.zip
> 
> Thanks!

On 2011-12-30 01:25:46 +0000, Ryan C. Gordon wrote:

> 
> Bumping priority on a few bugs that I would like examined more closely before 1.2.15 is finalized. This is not a promise that a bug will be fixed. We may close it with WONTFIX or WORKSFORME or something, but I just want to make sure attention is paid.
> 
> --ryan.

On 2014-12-12 02:59:45 +0000, Kerrigan Bangs wrote:

> Created attachment 1967
> Updated patch
> 
> The original fix by the original reporter did not work for me. I made my own fix.

On 2014-12-12 03:00:22 +0000, Kerrigan Bangs wrote:

> I know it's quite late but I know the precise cause of this problem:
> 
> The mmjoystick method is written with the assumption that all joystick axes are contiguous.
> 
> This is normally true, however apparently the Z axis is allowed to be skipped. (Source: http://msdn.microsoft.com/en-us/library/windows/hardware/ff543445%28v=vs.85%29.aspx at "No Holes" rule)
> 
> More recently this problem also affects the Saitek X55 joystick, as its rudder axis is not detected, since the joysticks skips the Throttle axis.
> 
> I have attached my own solution as the originally attached fix does not seem to work for me. Also, only the Z axis is allowed to be unmapped, so further checks afterward are not necessary assuming the axis count is correct.
> 
> Note that this problem is still present in SDL2, for the mmjoystick method. It doesn't happen in the DX Joystick method. Still, it's easy enough to fix anyways, I think.

On 2015-08-25 09:38:23 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting several copies of this message by email, since we are closing many bugs at once here.
> 
> We have decided to mark all SDL 1.2-related bugs as RESOLVED ENDOFLIFE, as we don't intend to work on SDL 1.2 any further, but didn't want to mark a large quantity of bugs as RESOLVED WONTFIX, to clearly show what was left unattended to and make it easily searchable.
> 
> Our current focus is on SDL 2.0.
> 
> If you are still having problems with an ENDOFLIFE bug, your absolute best option is to move your program to SDL2, as it will likely fix the problem by default, and give you access to modern platforms and tons of super-cool new features.
> 
> Failing that, we _will_ accept small patches to fix these issues, and put them in revision control, although we do not intend to do any further official 1.2 releases.
> 
> Failing that, please feel free to contact me directly by email (icculus@icculus.org) and we'll try to find some way to help you out of your situation.
> 
> Thank you,
> --ryan.

**Comment by sezero** [comment]
Attaching patch (based on the one by Kerrigan Bangs) that applies to current tree,
with an additional check for `j` against `MAX_AXES` to be safe.  Also attaching a patch
against the 2.0 tree.

[patch-1.2.txt](https://github.com/libsdl-org/SDL-1.2/files/5982293/patch-1.2.txt)
[patch-2.0.txt](https://github.com/libsdl-org/SDL-1.2/files/5982294/patch-2.0.txt)

**Comment by sezero** [comment]
Working MSDN documentation link from wayback machine:
https://web.archive.org/web/20190515120558/https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/special-case-mappings

**Comment by sezero** [comment]
@slouken, @icculus: I don't know if winmm joystick driver is still relevant in SDL2.
If it is, I posted an SDL2 version of the patch for this above -- not run-tested (no
hardware.)

**Comment by icculus** [comment]
Actually, this is a good question: is there ever a system that would use winmm in modern times? Surely this was for like...win95 machines without DirectX installed...?

**Comment by slouken** [comment]
Yeah, I think we can remove the winmm driver now.

**Comment by sezero** [comment]
> Yeah, I think we can remove the winmm driver now.

I can do that: Please make sure the following is correct and leaves no room for corner cases - I will handle the rest then.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 00f16d1..725ed33 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1713,15 +1713,16 @@ elseif(WINDOWS)
   if(SDL_HIDAPI)
     CheckHIDAPI()
   endif()
 
   if(SDL_JOYSTICK)
+    file(GLOB JOYSTICK_SOURCES ${SDL2_SOURCE_DIR}/src/joystick/windows/*.c)
+    set(SOURCE_FILES ${SOURCE_FILES} ${JOYSTICK_SOURCES})
+
     if(NOT WINDOWS_STORE)
       set(SDL_JOYSTICK_RAWINPUT 1)
     endif()
-    file(GLOB JOYSTICK_SOURCES ${SDL2_SOURCE_DIR}/src/joystick/windows/*.c)
-    set(SOURCE_FILES ${SOURCE_FILES} ${JOYSTICK_SOURCES})
     if(HAVE_DINPUT_H)
       set(SDL_JOYSTICK_DINPUT 1)
       list(APPEND EXTRA_LIBS dinput8)
     endif()
     if(HAVE_XINPUT_H)
@@ -1729,13 +1730,10 @@ elseif(WINDOWS)
       set(HAVE_XINPUT TRUE)
       if(HAVE_WINDOWS_GAMING_INPUT_H)
         set(SDL_JOYSTICK_WGI 1)
       endif()
     endif()
-    if(NOT HAVE_DINPUT_H AND NOT HAVE_XINPUT_H)
-      set(SDL_JOYSTICK_WINMM 1)
-    endif()
     set(HAVE_SDL_JOYSTICK TRUE)
 
     if(SDL_HAPTIC)
       if(HAVE_DINPUT_H OR HAVE_XINPUT_H)
         file(GLOB HAPTIC_SOURCES ${SDL2_SOURCE_DIR}/src/haptic/windows/*.c)
diff --git a/configure.ac b/configure.ac
index 7e4b92c..f5a6ead 100644
--- a/configure.ac
+++ b/configure.ac
@@ -3913,12 +3913,10 @@ case "$host" in
                 fi
                 if test x$have_dinput = xyes; then
                     AC_DEFINE(SDL_JOYSTICK_DINPUT, 1, [ ])
                     EXTRA_LDFLAGS="$EXTRA_LDFLAGS -ldinput8 -ldxguid -ldxerr8"
                 fi
-            else
-                AC_DEFINE(SDL_JOYSTICK_WINMM, 1, [ ])
             fi
             SOURCES="$SOURCES $srcdir/src/joystick/windows/*.c"
             have_joystick=yes
         fi
         if test x$enable_haptic = xyes; then
```

**Comment by sezero** [comment]
> Yeah, I think we can remove the winmm driver now.

Pushed https://github.com/libsdl-org/SDL/commit/f8900583e5c604f0eef6a3df04d86817dd0d8964
