### ISSUE TITLE
SDL_ConvertSurface not works on ppc64le

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#770]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.15
**Reported for operating system, platform:** Linux, PowerPC

# Comments on the original bug report:

On 2017-12-24 17:37:09 +0000, Andrei Karas wrote:

> If try to use SDL_ConvertSurface for convert pixel format from RRGGBBAA to AABBGGRR it do nothing on ppc64el.
> 
> This part of code from unit tests:
> 
> Same code here: https://gitlab.com/manaplus/manaplus/blob/dc3c3595855252304a18d15d6c90dcb98927036e/src/unittests/sdl.cc#L183-256
> 
> On ppc64el pixels not converted at all. For all other supported by debian arches this test passed. Also classical ppc works fine too (in QEMU).
> 
> Error build log from debian build system: https://buildd.debian.org/status/fetch.php?pkg=manaplus&arch=ppc64el&ver=1.7.11.11-1&stamp=1511365837&raw=0
> (see line unittests/sdl.cc:238: FAILED:)
> 
> Here all debian builds: https://buildd.debian.org/status/package.php?p=manaplus

On 2018-01-03 18:03:14 +0000, Sam Lantinga wrote:

> Do you have a patch? I don't have access to a ppc64el machine for debugging.

On 2018-01-03 18:14:56 +0000, Andrei Karas wrote:

> sadly no. I not sure what and where to change.

On 2018-01-03 18:36:44 +0000, Sam Lantinga wrote:

> Can you debug on the system? I can walk you through it, if you want.

On 2018-01-03 19:09:34 +0000, Andrei Karas wrote:

> I can use qemu. it slow.
> But can try to follow some instructions.

On 2018-01-03 21:57:57 +0000, Sam Lantinga wrote:

> Maybe you can instead give me instructions on setting up qemu to reproduce this?

On 2018-01-04 00:10:45 +0000, Andrei Karas wrote:

> I did install long ago, can forgot something. But here steps:
> 1. create disk for vm. I using 10GB qcow2 format
> 2. download iso http://d-i.debian.org/daily-images/ppc64el/daily/netboot/mini.iso
> 3. run qemu with this command (using 4 cores):
> 
> qemu-system-ppc64 \
> -smp cores=4,threads=1,sockets=1 \
> -m 2048 \
> -balloon virtio \
> -hda /path/disk.qcow2 \
> -cdrom /path//mini.iso \
> -netdev user,id=user.0 -device e1000,netdev=user.0
> 
> 4. install debian.
> I installed with DE/WM but all work did in console. Using env variable: SDL_VIDEODRIVER=dummy
> 
> If something not works, i can try upload my image.

On 2018-02-14 06:37:04 +0000, Ozkan Sezer wrote:

> Is this, by any chance, RedHat/Fedora bug # 1392465 ?
> https://bugzilla.redhat.com/show_bug.cgi?id=1392465
> https://src.fedoraproject.org/cgit/rpms/SDL.git/tree/SDL-1.2.15-vec_perm-ppc64le.patch

On 2018-02-21 22:11:17 +0000, Andrei Karas wrote:

> No, this patch not fixed SDL_ConvertSufrace. Probably it may fix other issues, but my tests stopped at SDL_ConvertSufrace.

**Comment by slouken** [comment]
Please open a new issue for SDL2 if that is still affected. We don't have a ppcle system to test with, so patches are appreciated.
