### ISSUE TITLE
SDL source code not up to date on website

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#771]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.15
**Reported for operating system, platform:** macOS 10.12, x86

# Comments on the original bug report:

On 2018-02-09 16:18:52 +0000,  wrote:

> Hello,
> 
> A package I was compiling on macOS had SDL 1.2 32-bits as a dependency.
> 
> I downloaded the source from here, see "SDL-1.2.15.zip - GPG signed":
> https://www.libsdl.org/download-1.2.php
> 
> The compilation of SDL 1.2 failed because of a bug that was resolved years ago:
> https://bugzilla.libsdl.org/show_bug.cgi?id=2085
> 
> I had to manually apply the patch in order to compile the library.
> 
> How was I supposed to download the latest version of SDL1.2? Is there a reason that the source isn't up to date?
> 
> Thank you

**Comment by sezero** [comment]
You can clone the https://github.com/libsdl-org/SDL-1.2 git repository.

**Comment by icculus** [comment]
The website 1.2 download page says "historic" but we should probably put a stronger "this was released in 2012, you need to go to revision control for fixes now, and please stop using this" message on there. I'm going to move this bug to the sdlweb issue tracker.
