### ISSUE TITLE
macOS keystroke receiving security popup

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#826]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 1.2
**Reported for operating system, platform:** macOS 10.15, x86_64

# Comments on the original bug report:

On 2020-08-05 20:49:52 +0000, Dominik Reichardt wrote:

> DOSBox still uses SDL 1.2x and when you open the DOSBox app a system dialog pops up:
> 
> "Keystroke receiving:
> Dosboxsvn.app would like to receive keystrokes from any application.
> Grant access to this application in Security& Privacy preferences, located in System Preferences."
> every time, no matter wheter you deny it or grant access. I know you fixed it for SDL2, maybe you can fix this for SDL 1.2x, too.

On 2020-12-13 22:31:38 +0000, Ozkan Sezer wrote:

> Ryan, do you have a patch for this?
> 
> (Which commit fixed it for SDL-2.x?)

On 2020-12-14 17:55:23 +0000, Cameron Gutman wrote:

> The patch for SDL2 was https://hg.libsdl.org/SDL/rev/6a3b2cc9d66c

On 2020-12-21 13:26:59 +0000, Ozkan Sezer wrote:

> (In reply to Cameron Gutman from comment # 2)
> > The patch for SDL2 was https://hg.libsdl.org/SDL/rev/6a3b2cc9d66c
> 
> I see. Code is completely different between 1.2 and 2.0...

**Comment by sezero** [comment]
@icculus, @slouken: Can you help with this? This is one of the few 1.2 issues
worth fixing.

**Comment by icculus** [comment]
I'm assigning this to me, but I'm buried in other work right now, so feel free to steal it back if you get there before me.
