### ISSUE TITLE
Reevaluate endoflife bugs

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL-1.2#837]
A long time ago, on Bugzilla, we closed a bunch of long-standing 1.2 bugs with a new resolution: ENDOFLIFE.

This was to say "this bug might be valid but we are no longer developing on SDL 1.2" and we wanted them gone from our list of open SDL bugs.

But since then, we split out 1.2 to a different repo with its own issue tracker on GitHub--so we don't have that problem anymore--and occasionally people _do_ fix 1.2 bugs.

So this is not something _I_ want to do, but if someone is so inclined, looking through the issues that have this label would be worth doing...

https://github.com/libsdl-org/SDL-1.2/issues?q=is%3Aissue+label%3Aendoflife

...if it's worth fixing (***AND NOT ALL OF THEM ARE***), then reopen the bug and remove the 'endoflife' label. If it's not, swap that label out with 'wontfix' and leave it closed.

The goal is to end up with a set of open, unlabeled bugs, and a bunch of closed, wontfix bugs.

If you sort through these, you aren't going to be required to _fix_ any of them, just need someone to sort through them. They can live here forever, open and unassigned.

Any volunteers?

**Comment by sezero** [comment]
Browsing the list, I might be looking at at least #592, #673, #684, #685, #706, #727.
