### ISSUE TITLE
Windows: different line endings 

### ISSUE THREAD

**Issue by carlo-bramini** [libsdl-org/SDL-1.2#844]
I made few fixes to `SDL-1.2/src/video/wincommon/SDL_sysevents.c` but github complains the fact that the file as mixed line ending, see attached screenshot.
It would be worth to normalize them, othewise my diff file is unreadable.
![SDL](https://user-images.githubusercontent.com/30959007/130759772-b417cc6b-1c5a-4753-81aa-f40ceb7e1472.png)

**Comment by sezero** [comment]
`video/wincommon/SDL_sysevents.c` has unix line endings, like any other file in SDL source tree. Run `dos2unix` on your modified version and the diff will be readable.

**Comment by ccawley2011** [comment]
PR #845 should fix it. There were only a couple of lines in that file that used CRLF.
