### ISSUE TITLE
[WINCE] Hardware keys are unmapped.

### ISSUE THREAD

**Issue by carlo-bramini** [libsdl-org/SDL-1.2#850]
Windows Mobile allows to use up to six hardware keys that can be mapped to various functions or used directly by applications:

https://docs.microsoft.com/en-us/previous-versions/bb431750(v=msdn.10)?redirectedfrom=MSDN

When you press/release these hardware keys, Windows returns a virtual scancode from VK_APP1 to VK_APP6, but they are unhandled by SDL1 at the moment.

Those virtual keys have values from 0xC1 to 0xC6 and, on traditional Windows, those scancodes are unssigned:

https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

It is not difficult to fix this issue, but the problem is that I have not found suitable "SDLK_" virtual keys to be used for them.

At the moment, in my local source tree, I mapped VK_APP1 to VK_APP6 to return SDLK_F1 to SDLK_F6, but I doubt that this could be accepted into official tree.

Have you some suggestions for fixing this thing?

Adding some SDLK_APP1 to SDLK_APP6 would be good?
Or importing some virtual codes from SDL2?
Or using other existing "SDLK_" macros?
Other solutions?

Thank you.

**Comment by sezero** [comment]
Missed this for quite some time as it seems.

I am not sure addition of new `SDLK_???` keys would be acceptable.
We _might_ fill in the gaps in `SDLKey` enum list with those keys
(e.g. between `SDLK_DELETE` and `SDLK_WORLD_0` maybe??)
guarded by `_WIN32_WCE` -- that would be another method of
adding new `SDLK_???` keys but at least SDLK_LAST won't change.

In any case, I am not sure what would be acceptable. @slouken?

**Comment by slouken** [comment]
For now mapping to F1-F6 is fine.

**Comment by sezero** [comment]
@carlo-bramini: send patches (or pull-requests)
