### ISSUE TITLE
SDL doesn't render anything on MacOSX 11.5.1

### ISSUE THREAD

**Issue by LanFly** [libsdl-org/SDL-1.2#851]
## environment

SDL: 1.2.15
gcc: Apple clang version 13.0.0 (clang-1300.0.29.3)

## SDL doesn't render anything on MacOSX 11.5.1.

I confirm that the picture exists.

## result: nothing
![image](https://user-images.githubusercontent.com/7923987/141946103-ef1f461f-1830-4cdd-9393-615dd3df07f6.png)

## code: src/window.c
```c
#include <SDL/SDL.h>

#undef main
int main(int argc, char *argv[])
{
  SDL_bool quit = SDL_FALSE;
  SDL_Event event;
  SDL_Init(SDL_INIT_EVERYTHING);

  SDL_Rect rect = {0, 0, 100, 100};
  
  SDL_Surface* window = SDL_SetVideoMode(480, 480, 32, SDL_SWSURFACE);
  SDL_Surface* hello = SDL_LoadBMP("../preview2.bmp");
  if (hello == NULL) {
    printf("read bmp error\n");
  }
  SDL_BlitSurface(hello, NULL, window, NULL);
  SDL_WM_SetCaption("hello sdl", "logo.png");
  SDL_Flip(window);

  while (!quit)
  {
    while (SDL_PollEvent(&event))
    {
      if (event.type == SDL_QUIT) {
        quit = SDL_TRUE;
      }
    }
  }
  
  SDL_FreeSurface(hello);
  SDL_Quit();
  return 0;
}
```

## CMakeLists.txt

```
cmake_minimum_required(VERSION 3.5)
set(project_name sdl-demo)
project(${project_name})

add_executable(${project_name} src/window.c)
target_include_directories(${project_name} PUBLIC ~/Library/SDL ~/Library)

target_link_libraries(${project_name} /Users/lan/Library/SDL/SDL)
```

**Comment by slouken** [comment]
@icculus, @sezero, does sdl12-compat work on macOS?

**Comment by sezero** [comment]
> @icculus, @sezero, does sdl12-compat work on macOS?

As far as I know, yes.

**Comment by sezero** [comment]
> SDL: 1.2.15 gcc: Apple clang version 13.0.0 (clang-1300.0.29.3)

I suggest trying SDL-1.2 from git instead of the 1.2.15 release.

**Comment by icculus** [comment]
sdl12-compat and the latest in git both work, to my knowledge.

1.2.15 is broken on newer macOS releases, and has been for quite some time now.

**Comment by LanFly** [comment]
thank's all. I resolved the problem with recompile sdl1.2 and link libSDLmain.a.

**Comment by sezero** [comment]
OK, closing.
