### ISSUE TITLE
[WINDIB vs. Windows 8+] SDL_SetVideoMode fails (freezes)

### ISSUE THREAD

**Issue by pionere** [libsdl-org/SDL-1.2#856]
Calling SDL_SetVideoMode with (640, 480, 0, SDL_FULLSCREEN) freezes the application on Windows 8.1 with windib video driver.

The reason is ChangeDisplaySettingsA does not return on line 763 in SDL_dibvideo.c . Tried add CDS_TEST to the flags and that seems to work, but as soon as the display would be changed the function does not return.
Without SDL_FULLSCREEN the application runs just fine too.

According to Microsoft, the [minimum](https://www.c-sharpcorner.com/news/coming-windows-8-with-1024x768-minimum-resolution) [resolution](https://www.onmsft.com/news/what-minimum-and-maximum-screen-resolution-windows-8) of the applications is 1024x768 from [Windows 8](https://news.softpedia.com/news/Windows-8-Comes-with-1024x768-Minimum-Resolution-No-Maximum-Limit-260356.shtml)+. It seems that they forgot to update ChangeDisplaySettingsA to reflect on this new requirement.

Apparently they dropped this requirement in Windows 10...

**Comment by pionere** [comment]
After some investigation I found the followings.
There seems to be a minimum required resolution for each windows version ([wiki](https://en.wikipedia.org/wiki/Comparison_of_Microsoft_Windows_versions#Hardware_requirements)):
Version | Resolution
---------|------------
Windows XP, Vista | 800x600 [?](https://support.norton.com/sp/en/us/home/current/solutions/kb20090213153745EN)
Windows 7, 8, 8.1 | 1024x768 [?](https://support.norton.com/sp/en/us/home/current/solutions/kb20090213153745EN)
Windows 10 |  [800x600](https://download.microsoft.com/download/c/1/5/c150e1ca-4a55-4a7e-94c5-bfc8c2e785c5/Windows%2010%20Minimum%20Hardware%20Requirements.pdf)
Windows 11 |  [1280x720](https://download.microsoft.com/download/7/8/8/788bf5ab-0751-4928-a22c-dffdc23c27f2/Minimum%20Hardware%20Requirements%20for%20Windows%2011.pdf)

EnumDisplaySettings still reports valid resolutions from 320x200.
ChangeDisplaySettings(Ex) reports DISP_CHANGE_SUCCESSFUL for resolutions from 320x200 (Probably uses EnumDisplaySettings) if run with CDS_TEST.
ChangeDisplaySettings freezes when trying to set resolution to 640x480.
The lowest available resolution is 1024x768 in the Control Panel on my system (Windows 8.1)

**Comment by sezero** [comment]
@icculus, @slouken: Anything to do with this?

**Comment by slouken** [comment]
Is this an issue with sdl12-compat?

**Comment by pionere** [comment]
No, sdl1.2. SDL2 works fine with d3d.

**Comment by slouken** [comment]
I recommend you use SDL12-compat, which will be future proof against these kinds of issues. @icculus is working on creating an official release which will be a drop-in replacement for SDL 1.2.
