### ISSUE TITLE
Need help building the Win32 binary SDL.dll

### ISSUE THREAD

**Issue by Spatzendame** [libsdl-org/SDL-1.2#858]
Hello,

I've already red all the tutorials, but I still failed to build the binaries using the latest Microsoft Visual Studio 2022 Community.
I get errors in the building process and then no dll will be built. What am I doing wrong?
Please can someone explain to me exactly how to build the SDL.dll ?

I need it from the latest source code, because it contains all the important fixes that were made after the 1.2.15 release since 2012.
Maybe someone here can build the dll for me from this source code here?

I also want to do the same thing with the "SDL12-compat" source code.

Thank you very much for your help.

**Comment by sezero** [comment]
Go into the `include` directory and copy `SDL_config.h.default` as `SDL_config.h`: that _is_ the step you have been missing. Then go into the `VisualC` directory and run the `SDL_VS2010.sln` solution file: it will work with VS2022 community edition - I just built it myself.

**Comment by Spatzendame** [comment]
Hey, thank you so much, this really worked. Now I have the SDL.dll version 1.2.16.0.
Have you fixed the mouse bug that occured in Windows 10 Creators Update and "Amnesia: The Dark Descent"?
I know Microsoft and Frictional Games finally fixed it in their software, but SDL itself didn't get a native fix so I hope the source code got the fix. The old SDL 1.2.13.0 was that one with working mouse back in the days.

And now I want to create the SDL12-compat binaries too. Linking SDL2 to CMake is the problem and other errors in VS2022.
