### ISSUE TITLE
DirectFB causes apps to crash.

### ISSUE THREAD

**Issue by fifteenhex** [libsdl-org/SDL-1.2#859]
I'm still trying to work out the root cause of this but this is what I have so far:
- DirectFB itself works fine, the native DirectFB demos work on the targets (armhf and amd64)
- The apps seem to be OK as they work when using the fbdev backend
- The apps seem to crash because they are getting a null pointer for the framebuffer, they seem to get a workable address at some point because you can see stuff getting drawn to the screen
- The problem seems to come right after the framebuffer mode is getting changed.

FWIW: I know SDL1 is dead, DirectFB was basically dead too (it's recently been forked and getting some love again), the target platform can only run SDL2 with the DirectFB backend because it doesn't have a GPU to run the KMSDRM backend. I also want to run some SDL1 apps that haven't been ported... so getting the DirectFB backend working is the easiest route to having both SDL2 and SDL1 working on this machine.

**Comment by sezero** [comment]
The directfb backend in SDL1.2 hasn't been touched since 10 years. Do you have a patch? Does the directfb backend in SDL2 work properly?

**Comment by fifteenhex** [comment]
> The directfb backend in SDL1.2 hasn't been touched since 10 years. Do you have a patch?
>Does the directfb backend in SDL2 work properly?

I don't have a patch yet. I will send something once I figure it out.
Not tried SDL2 yet.

**Comment by fifteenhex** [comment]
Small update: SDL2 works ok.
https://twitter.com/linux_chenxing/status/1492708033763635202

**Comment by sezero** [comment]
Is the crash a segfault? Any backtrace?

> I don't have a patch yet. I will send something once I figure it out.

Would be appreciated.

**Comment by fifteenhex** [comment]
> Is the crash a segfault? Any backtrace?

Yeah, segfault from trying to do memset() to 0x0.

**Comment by sezero** [comment]
> Yeah, segfault from trying to do memset() to 0x0.

A backtrace ?

**Comment by fifteenhex** [comment]
Sorry, don't have a backtrace yet. The original system is a bit too small to install everything with debug symbols etc.
So I've been getting the whole stack working on to of QEMU to chase down the issue.

Anyhow I think I might have found it, it looks like some apps want to get the memory mapped address of the framebuffer to write directly into it. With the drmkms backend for directfb that is currently unsupported and returns 0. If the app doesn't check the return value things go badly. Once I get gdb etc working I'll confirm that... potentially I can fix directfb.

**Comment by Apaczer** [comment]
The DirectFB2 seems to work either with SDL1.2.15 or latest SDL2 (dare to say former is even more stable). That is on old ARMv5 chipset with no GPU. 
Not sure if there were signiffact changes since then in the directfb2/directfb2 upstream, but until there is no fbcon in SDL2 branch then the DirectFB2 is far from dead

**Comment by Apaczer** [comment]
try to unset SDL_DOUBLEBUF or TRIPLEBUF flags when using directfb driver, because it usually leads to segfault before launch or at quit when freeing surface. No such issue when using fbcon
