### ISSUE TITLE
Interoperability between SDL1.2 apps and SDL2 plugins on macOS

### ISSUE THREAD

**Issue by kjliew** [libsdl-org/SDL-1.2#864]
The patch enables retrievable `info->nsWindowPtr` type from SDL_GetWMInfo() to enable foreign window conversion in SDL2 plugins. Fixed class collision warning on `SDLTranslatorResponder` when both SDL1.2 and SDL2 dylib are loaded at the same time.

sha256sum 26d450371967cce1bd169c46cdedee1e98d2acd07dd14d1a25ee2aa7c2655779
[0005-GetWMInfo.txt](https://github.com/libsdl-org/SDL-1.2/files/9523059/0005-GetWMInfo.txt)

**Comment by sezero** [comment]
@slouken and @icculus will probably not like this and close as EOL.

**Comment by kjliew** [comment]
That's fine. It's for archiving.

**Comment by sezero** [comment]
I wonder why it was commented out, though..

**Comment by icculus** [comment]
I don't know why this is commented out, either, but it's literally never been uncommented:

https://github.com/libsdl-org/SDL-1.2/commit/924ec820df1a531a58b9fc582af1ac4bbf114fa0

It probably wouldn't hurt to change it, but also it's never going to be in a formal release or properly tested by us, so we'll just leave this as archival for now.

**Comment by CyberLuke-GBG** [comment]
@kjliew are you able to fix it in your branch? 

@icculus even no pull request will be merged?

**Comment by kjliew** [comment]
> @kjliew are you able to fix it in your branch?

It is just a waste of time doing that. Everyone should have moved to SDL2. Distros packagers can simply pull the patch from here and apply for themselves.

**Comment by cyberluke** [comment]
People at Vogons forum use it for retro computing (Windows 98) and on FreeDOS mailing list there are people running SDL in DOS as well.

**Comment by cyberluke** [comment]
Thank you for linking that, I will share it with others. Perhaps clonning this whole repo and applying this fix for others as well.
