### ISSUE TITLE
SDL-1.2 on Playstation 3 (Fedora 12 - OtherOS)

### ISSUE THREAD

**Issue by ModelCitizenPS3** [libsdl-org/SDL-1.2#876]
Hi. I'm trying to build SDL-1.2 on my Playstation 3 but the build fails when linking with the following error:

/usr/bin/ld: cannot find -lbilin_scaler_spu

I've been searching the Internet for anything resembling a libbilin_scaler_spu library with no luck, and I've thoroughly queried my package manager to search thru all the Cell SDKs I have access to, but have not found any package that provides such a file. Would be very cool if someone could shed some light on what I'm missing or doing wrong...

My setup is as follows: I'm on a phat (OtherOS) Playstation 3 running firmware 3.15 and my distro is Fedora 12 (ppc64). The Cell SDKs I have available are versions 3.1 (RHEL), 3.0 (Fedora), 2.1, and 2.0, and yum has access to them all. My configure command for the build is:

./configure --prefix=/usr/local --x-includes=/usr/include/X11 --x-libraries=/usr/lib --enable-video-ps3

Any help/info would be much appreciated. Thanx :-)

**Comment by icculus** [comment]
So, I have never used the SDL-1.2 PS3 code, or even know how to build it, but there's src/video/ps3/spulibs, and in there is a Makefile that appears to generate the libraries you need.

**Comment by icculus** [comment]
Assuming we can close this issue for now. If you try this and run into problems, let us know, though!
