### ISSUE TITLE
SDL1.x - which version supports NT3.1 or Win3.1?

### ISSUE THREAD

**Issue by Torinde** [libsdl-org/SDL-1.2#885]
SDL 2004 website [FAQ What Platforms are Supported](https://web.archive.org/web/20041211005740/http://www.libsdl.org/cgi/docwiki.cgi/FAQ_20What_20Platforms_20are_20Supported) is not archived and I can't find information which version (if any) of SDL supports those:
- Windows NT3.1
- Windows 3.1x with Win32s

Closest I found is [here](https://www.vogons.org/viewtopic.php?p=710400#p710400):
> Lowest SDL 1.2.13 supports is 95 (original) (unknown about betas) and NT 3.50 (Have to disable fullscreen support and use 3.51 joystick dll.)

**Comment by icculus** [comment]
I'm not sure that NT3.1 or Win32s was _ever_ supported; that vogons.org post was saying that the author had personally patched it to work on NT3.1 (and that HX DOS Extender could run his Win95 build with its Win32s support). It's not impossible that the windib video backend would work on those platforms without changes, but even the winmm audio code needs to spin a thread internally, so it might work on ancient WinNT, but it's likely a non-starter on win32s in any case.

But there are fallbacks for platforms without DirectX at all, so with work one could probably get it running, maybe disabling audio.

SDL 1.2 (even the latest in revision control, afaik) should still work on Windows 95 and WinNT 4.0, but no one here is testing these platforms any more (or SDL 1.2 at all, really, at this point).

**Comment by ccawley2011** [comment]
I did get SDL 1.2 working on Windows 3.1 with Win32s and WinG a while ago: https://github.com/ccawley2011/SDL-1.2/tree/win32s

![krnl386_030](https://github.com/libsdl-org/SDL-1.2/assets/19293424/3dcf5a67-5628-47d4-9d89-5a0bf834e708)

**Comment by sezero** [comment]
> I did get SDL 1.2 working on Windows 3.1 with Win32s and WinG a while ago: https://github.com/ccawley2011/SDL-1.2/tree/win32s

Huh. So it was possible..

**Comment by Torinde** [comment]
@icculus, thank you for the details!
What I found afterwards:
- [Changelog SDL 0.9.0 to 1.2.7](https://web.archive.org/web/20041207041746/http://www.libsdl.org/release/changes-1.2.html): no explicit mention of NT3.1 or Win3.x
- [2002 FAQ What platforms are supported?](https://web.archive.org/web/20041116220930/http://www.libsdl.org/faq.php?action=listentries&category=1): "Windows"
- [2001 About SDL](https://web.archive.org/web/20041205214158/http://sdldoc.csn.ul.ie/guidepreface.php#GUIDEABOUTSDL): "Win32"
- [2002 FAQ Auf welchen Plattformen läuft SDL?](https://web.archive.org/web/20041203170250/http://www.libsdl.de/): "Windows (32 Bit)"

Remains inconclusive - neither official mention of NT3.1/Win3.x/Win32**s**, nor explicit "can't be done" statement.

@ccawley2011, wow, great job - pleasant surprise while I was writing this! That settles it!
Are you interested in adapting DOSbox-X for Win32s+WinG? Some discussions about adapting it for [NT3.5x](https://github.com/joncampbell123/dosbox-x/pull/4612#issuecomment-2179387193) and [Win32s](https://github.com/joncampbell123/dosbox-x/pull/4612#issuecomment-1834436936):
> If SDL is using the top-down BITMAPINFO type blitting that doesn't work either in Windows 3.1 and you'll get an emulator screen that's upside down.

Do you know if SDL is using top-down BITMAPINFO type blitting?
Did you get the audio working as well?

**Comment by icculus** [comment]
> I did get SDL 1.2 working on Windows 3.1 with Win32s and WinG a while ago:

Okay, well, holy shit.   :)

**Comment by Dima120596** [comment]
Russian: https://github.com/Dima120596/SDL1.2.15-fork-NT-3.1--Alchimik- - готовый порт SDL 1.2.15 для NT 3.1, можете взять как дополнение.
https://github.com/Dima120596/SDL1.2.15-fork-NT-3.1--Alchimik- - a ready-made port of SDL 1.2.15 for NT 3.1, you can take it as an addition.
